domain: webteam-ircbot.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/webteam-ircbot.canonical.com
replicas: 1

readinessPath: false

memoryLimit: 128Mi

env:

  - name: MATTERMOST_USER
    value: "webbot"
  - name: MATTERMOST_HOST
    value: "chat.canonical.com"
  - name: MATTERMOST_GROUP
    value: "canonical"
  - name: HUBOT_RELEASE_NOTIFICATION_ROOMS
    value: "is-outage"
  - name: HUBOT_IRC_DEBUG
    value: "true"
  - name: HUBOT_SPREADSHEET_CLIENT_EMAIL
    value: "webbotac@webbot-262415.iam.gserviceaccount.com"
  - name: HUBOT_SPREADSHEET_ID
    value: "1nNk4typDnOfDEYRzlEjtd58zk-aOd3_NNp6eufthZHM"
  - name: SENTRY_DSN
    value: https://581b9553f22846578ec60b24c62d7d25@sentry.is.canonical.com//41
  - name: HUBOT_AUTH_ADMIN
    secretKeyRef:
      key: hubot-auth-admin
      name: irc-secrets
  - name: JENKINS_URL
    secretKeyRef:
      key: jenkins-url
      name: webteam-jenkins
  - name: JENKINS_TOKEN
    secretKeyRef:
      key: jenkins-token
      name: webteam-jenkins
  - name: MATTERMOST_ACCESS_TOKEN
    secretKeyRef:
      key: mattermost-access-token
      name: irc-secrets
  - name: HUBOT_RELEASE_NOTIFICATION_SECRET
    secretKeyRef:
      key: hubot-release-notification-secret
      name: irc-secrets
  - name: HUBOT_SPREADSHEET_PRIVATE_KEY
    secretKeyRef:
      key: hubot-spreadsheet-private-key
      name: irc-secrets
  - name: HUBOT_GITHUB_TOKEN
    secretKeyRef:
      key: hubot-github-token
      name: irc-secrets
  - name: MATTERMOST_TOKEN_CMD_ACRONYM
    secretKeyRef:
      key: hubot-mattermost-token-cmd-acronym
      name: irc-secrets
  - name: MATTERMOST_TOKEN_CMD_MEET
    secretKeyRef:
      key: hubot-mattermost-token-cmd-meet
      name: irc-secrets
  - name: MATTERMOST_TOKEN_CMD_DIR
    secretKeyRef:
      key: hubot-mattermost-token-cmd-dir
      name: irc-secrets
  - name: MATTERMOST_TOKEN_CMD_TZ
    secretKeyRef:
      key: hubot-mattermost-token-cmd-tz
      name: irc-secrets
  - name: DISCOURSE_WEBHOOK_SECRET
    secretKeyRef:
      key: discourse-webhook-secret
      name: irc-secrets
  - name: GRAFANA_USERNAME
    secretKeyRef:
      key: grafana-username
      name: irc-secrets
  - name: GRAFANA_PASSWORD
    secretKeyRef:
      key: grafana-password
      name: irc-secrets
  - name: MATTERMOST_TOKEN_CMD_EXPLAIN
    secretKeyRef:
      key: hubot-mattermost-token-cmd-explain
      name: irc-secrets
